"""
server/db/models.py — SQLAlchemy ORM models for the Trading Bot.

Tables:
  users           — accounts, roles, and auth state
  api_keys        — per-user programmatic API keys
  trades          — every executed (or simulated) trade with full audit trail
  positions       — currently open positions (live state)
  signals         — every signal generated by the bot
  strategy_configs — saved strategy parameter sets
  backtest_results — stored backtest runs with equity curves
  audit_logs      — security and activity audit trail
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import (
    Boolean, DateTime, Float, ForeignKey, Integer,
    String, Text, JSON, Index, UniqueConstraint,
    Enum as SAEnum,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from server.db.database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _uuid() -> str:
    return str(uuid.uuid4())


# ─── ENUMS ────────────────────────────────────────────────────────────────────

class UserRole(str):
    ADMIN  = "admin"    # full access: manage users, view all data
    TRADER = "trader"   # run bot, execute trades, view own data
    VIEWER = "viewer"   # read-only: dashboards and reports


class TradeStatus(str):
    PENDING   = "pending"
    OPEN      = "open"
    CLOSED    = "closed"
    CANCELLED = "cancelled"
    REJECTED  = "rejected"


class TradeSide(str):
    BUY  = "buy"
    SELL = "sell"


class SignalType(str):
    BUY  = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


# ─── USERS ────────────────────────────────────────────────────────────────────

class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=_uuid
    )
    email: Mapped[str]    = mapped_column(String(255), unique=True, nullable=False, index=True)
    username: Mapped[str] = mapped_column(String(100), unique=True, nullable=False, index=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[str]     = mapped_column(String(20), default="trader", nullable=False)
    is_active: Mapped[bool]    = mapped_column(Boolean, default=True, nullable=False)
    is_verified: Mapped[bool]  = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now, nullable=False
    )
    last_login: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    failed_login_attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    locked_until: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    api_keys: Mapped[list[ApiKey]]              = relationship("ApiKey", back_populates="user", cascade="all, delete-orphan")
    trades: Mapped[list[Trade]]                 = relationship("Trade", back_populates="user", cascade="all, delete-orphan")
    positions: Mapped[list[Position]]           = relationship("Position", back_populates="user", cascade="all, delete-orphan")
    signals: Mapped[list[Signal]]               = relationship("Signal", back_populates="user", cascade="all, delete-orphan")
    strategy_configs: Mapped[list[StrategyConfig]] = relationship("StrategyConfig", back_populates="user", cascade="all, delete-orphan")
    backtest_results: Mapped[list[BacktestResult]] = relationship("BacktestResult", back_populates="user", cascade="all, delete-orphan")
    audit_logs: Mapped[list[AuditLog]]          = relationship("AuditLog", back_populates="user", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<User {self.username} [{self.role}]>"


# ─── API KEYS ─────────────────────────────────────────────────────────────────

class ApiKey(Base):
    __tablename__ = "api_keys"

    id: Mapped[str]       = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    user_id: Mapped[str]  = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    name: Mapped[str]     = mapped_column(String(100), nullable=False)
    key_prefix: Mapped[str]  = mapped_column(String(12), nullable=False)   # first 8 chars shown in UI
    key_hash: Mapped[str]    = mapped_column(String(255), nullable=False, unique=True)
    scopes: Mapped[list]     = mapped_column(JSON, default=list, nullable=False)  # ["read", "trade", "admin"]
    is_active: Mapped[bool]  = mapped_column(Boolean, default=True, nullable=False)
    last_used: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)

    user: Mapped[User] = relationship("User", back_populates="api_keys")


# ─── TRADES ───────────────────────────────────────────────────────────────────

class Trade(Base):
    """Full audit record of every trade (paper or live)."""
    __tablename__ = "trades"

    id: Mapped[str]       = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    user_id: Mapped[str]  = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    signal_id: Mapped[Optional[str]] = mapped_column(UUID(as_uuid=False), ForeignKey("signals.id"), nullable=True)

    # Core trade fields
    symbol: Mapped[str]      = mapped_column(String(30), nullable=False, index=True)
    side: Mapped[str]        = mapped_column(String(10), nullable=False)          # buy | sell
    order_type: Mapped[str]  = mapped_column(String(20), default="market", nullable=False)
    quantity: Mapped[float]  = mapped_column(Float, nullable=False)
    entry_price: Mapped[float]              = mapped_column(Float, nullable=False)
    exit_price: Mapped[Optional[float]]     = mapped_column(Float, nullable=True)
    stop_loss: Mapped[Optional[float]]      = mapped_column(Float, nullable=True)
    take_profit: Mapped[Optional[float]]    = mapped_column(Float, nullable=True)
    limit_price: Mapped[Optional[float]]    = mapped_column(Float, nullable=True)

    # Outcome
    status: Mapped[str]       = mapped_column(String(20), default="pending", nullable=False, index=True)
    pnl: Mapped[Optional[float]]            = mapped_column(Float, nullable=True)
    pnl_pct: Mapped[Optional[float]]        = mapped_column(Float, nullable=True)
    commission: Mapped[Optional[float]]     = mapped_column(Float, nullable=True)
    slippage: Mapped[Optional[float]]       = mapped_column(Float, nullable=True)

    # Attribution
    strategy: Mapped[Optional[str]]    = mapped_column(String(50), nullable=True)    # trend | momentum | mean_reversion | ai_model
    broker: Mapped[Optional[str]]      = mapped_column(String(50), nullable=True)    # bitoasis | ibkr | paper
    broker_order_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    is_paper: Mapped[bool]             = mapped_column(Boolean, default=True, nullable=False)

    # Discord confirmation
    discord_message_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    discord_confirmed: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    confirmed_by: Mapped[Optional[str]]       = mapped_column(String(100), nullable=True)

    # Extra context
    notes: Mapped[Optional[str]]  = mapped_column(Text, nullable=True)
    metadata_: Mapped[Optional[dict]] = mapped_column("metadata", JSON, nullable=True)

    # Timestamps
    opened_at: Mapped[datetime]           = mapped_column(DateTime(timezone=True), default=_now, nullable=False, index=True)
    closed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    updated_at: Mapped[datetime]          = mapped_column(DateTime(timezone=True), default=_now, onupdate=_now, nullable=False)

    # Relationships
    user: Mapped[User]               = relationship("User", back_populates="trades")
    signal: Mapped[Optional[Signal]] = relationship("Signal", back_populates="trades")

    __table_args__ = (
        Index("ix_trades_user_symbol", "user_id", "symbol"),
        Index("ix_trades_opened_at", "opened_at"),
    )

    def __repr__(self) -> str:
        return f"<Trade {self.side.upper()} {self.quantity} {self.symbol} @ {self.entry_price}>"


# ─── POSITIONS ────────────────────────────────────────────────────────────────

class Position(Base):
    """Currently open positions (live state, updated in real-time)."""
    __tablename__ = "positions"

    id: Mapped[str]      = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    trade_id: Mapped[Optional[str]] = mapped_column(UUID(as_uuid=False), ForeignKey("trades.id"), nullable=True)

    symbol: Mapped[str]       = mapped_column(String(30), nullable=False)
    side: Mapped[str]         = mapped_column(String(10), nullable=False)
    quantity: Mapped[float]   = mapped_column(Float, nullable=False)
    entry_price: Mapped[float]= mapped_column(Float, nullable=False)
    current_price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    stop_loss: Mapped[Optional[float]]     = mapped_column(Float, nullable=True)
    take_profit: Mapped[Optional[float]]   = mapped_column(Float, nullable=True)
    unrealized_pnl: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    unrealized_pnl_pct: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    broker: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    is_paper: Mapped[bool]        = mapped_column(Boolean, default=True, nullable=False)

    opened_at: Mapped[datetime]  = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, onupdate=_now, nullable=False)

    user: Mapped[User] = relationship("User", back_populates="positions")

    __table_args__ = (
        UniqueConstraint("user_id", "symbol", "broker", name="uq_position_user_symbol_broker"),
    )


# ─── SIGNALS ──────────────────────────────────────────────────────────────────

class Signal(Base):
    """Every signal generated by the bot's strategy aggregator."""
    __tablename__ = "signals"

    id: Mapped[str]      = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    symbol: Mapped[str]          = mapped_column(String(30), nullable=False, index=True)
    signal_type: Mapped[str]     = mapped_column(String(10), nullable=False)   # BUY | SELL | HOLD
    composite_score: Mapped[float] = mapped_column(Float, nullable=False)

    entry_price: Mapped[Optional[float]]        = mapped_column(Float, nullable=True)
    stop_loss: Mapped[Optional[float]]          = mapped_column(Float, nullable=True)
    take_profit: Mapped[Optional[float]]        = mapped_column(Float, nullable=True)
    position_size_pct: Mapped[Optional[float]]  = mapped_column(Float, nullable=True)

    # Per-strategy breakdown scores
    trend_score: Mapped[Optional[float]]          = mapped_column(Float, nullable=True)
    momentum_score: Mapped[Optional[float]]       = mapped_column(Float, nullable=True)
    mean_reversion_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ai_model_score: Mapped[Optional[float]]       = mapped_column(Float, nullable=True)
    markov_score: Mapped[Optional[float]]         = mapped_column(Float, nullable=True)

    strategy_breakdown: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    risk_check_passed: Mapped[Optional[bool]]  = mapped_column(Boolean, nullable=True)
    risk_reasons: Mapped[Optional[list]]       = mapped_column(JSON, nullable=True)

    data_source: Mapped[Optional[str]]   = mapped_column(String(50), nullable=True)
    interval: Mapped[Optional[str]]      = mapped_column(String(10), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False, index=True)

    # Relationships
    user: Mapped[User]       = relationship("User", back_populates="signals")
    trades: Mapped[list[Trade]] = relationship("Trade", back_populates="signal")

    __table_args__ = (
        Index("ix_signals_user_created", "user_id", "created_at"),
    )


# ─── STRATEGY CONFIGS ─────────────────────────────────────────────────────────

class StrategyConfig(Base):
    """Named, saved strategy configurations."""
    __tablename__ = "strategy_configs"

    id: Mapped[str]      = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    name: Mapped[str]          = mapped_column(String(100), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    config_json: Mapped[dict]  = mapped_column(JSON, nullable=False)
    is_active: Mapped[bool]    = mapped_column(Boolean, default=False, nullable=False)
    is_default: Mapped[bool]   = mapped_column(Boolean, default=False, nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, onupdate=_now, nullable=False)

    user: Mapped[User] = relationship("User", back_populates="strategy_configs")

    __table_args__ = (
        UniqueConstraint("user_id", "name", name="uq_strategy_config_user_name"),
    )


# ─── BACKTEST RESULTS ─────────────────────────────────────────────────────────

class BacktestResult(Base):
    """Stored backtest runs with full metrics and equity curves."""
    __tablename__ = "backtest_results"

    id: Mapped[str]      = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    name: Mapped[Optional[str]]  = mapped_column(String(100), nullable=True)
    symbols: Mapped[list]        = mapped_column(JSON, nullable=False)     # ["AAPL", "GOOGL"]
    interval: Mapped[str]        = mapped_column(String(10), nullable=False)
    period: Mapped[str]          = mapped_column(String(20), nullable=False)
    data_source: Mapped[str]     = mapped_column(String(50), nullable=False)

    config_json: Mapped[dict]    = mapped_column(JSON, nullable=False)     # full BotConfig snapshot
    metrics_json: Mapped[dict]   = mapped_column(JSON, nullable=False)     # per-symbol metrics
    equity_curve: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)   # [{date, equity}, ...]
    trades_summary: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)

    initial_capital: Mapped[float]       = mapped_column(Float, nullable=False)
    final_equity: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    total_return_pct: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    sharpe_ratio: Mapped[Optional[float]]     = mapped_column(Float, nullable=True)
    max_drawdown_pct: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    win_rate_pct: Mapped[Optional[float]]     = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False, index=True)
    duration_seconds: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    user: Mapped[User] = relationship("User", back_populates="backtest_results")


# ─── AUDIT LOGS ───────────────────────────────────────────────────────────────

class AuditLog(Base):
    """Immutable security and activity audit trail."""
    __tablename__ = "audit_logs"

    id: Mapped[str]               = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    user_id: Mapped[Optional[str]] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)

    action: Mapped[str]          = mapped_column(String(100), nullable=False, index=True)
    resource: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    resource_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    details: Mapped[Optional[dict]]    = mapped_column(JSON, nullable=True)
    ip_address: Mapped[Optional[str]]  = mapped_column(String(45), nullable=True)
    user_agent: Mapped[Optional[str]]  = mapped_column(String(255), nullable=True)
    status: Mapped[str]                = mapped_column(String(20), default="success", nullable=False)  # success | failure
    created_at: Mapped[datetime]       = mapped_column(DateTime(timezone=True), default=_now, nullable=False, index=True)

    user: Mapped[Optional[User]] = relationship("User", back_populates="audit_logs")

    __table_args__ = (
        Index("ix_audit_logs_created_at", "created_at"),
        Index("ix_audit_logs_action_status", "action", "status"),
    )
